/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.futuresoft.sistemamovagro_presentacion;

import com.futuresoft.sistemamovagro_dominio.Material;
import com.futuresoft.sistemamovagro_dominio.Proveedor;
import com.futuresoft.sistemamovagro_negocio.FachadaNegocio;
import com.futuresoft.sistemamovagro_negocio.INegocio;
import java.util.List;

/**
 *
 * @author jctri
 */
public class FrmAdministrarMaterial extends javax.swing.JFrame {
    INegocio negocio;
    /**
     * Creates new form FrmAdministrarMaterial
     */
    public FrmAdministrarMaterial() {
        negocio = new FachadaNegocio();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        btnConsultarMaterial = new javax.swing.JButton();
        btnBajaMaterial = new javax.swing.JButton();
        btnRegistrarMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(0, 153, 204));
        btnVolver.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 110, -1));

        labelTitle.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        labelTitle.setText("Administrar Material");
        jPanel1.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btnConsultarMaterial.setBackground(new java.awt.Color(0, 153, 204));
        btnConsultarMaterial.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnConsultarMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarMaterial.setText("Consultar Material");
        btnConsultarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMaterialActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 240, -1));

        btnBajaMaterial.setBackground(new java.awt.Color(0, 153, 204));
        btnBajaMaterial.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnBajaMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnBajaMaterial.setText("Baja Material");
        btnBajaMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaMaterialActionPerformed(evt);
            }
        });
        jPanel1.add(btnBajaMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 240, -1));

        btnRegistrarMaterial.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistrarMaterial.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnRegistrarMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarMaterial.setText("Registrar Material");
        btnRegistrarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMaterialActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMaterialActionPerformed
         List<Proveedor> proveedoresList = negocio.recuperaProveedor();
         FrmRegistrarMaterial regMat = new FrmRegistrarMaterial(proveedoresList);
         regMat.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnRegistrarMaterialActionPerformed

    private void btnBajaMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaMaterialActionPerformed
        List<Material> materialesList = negocio.recuperaMaterial();
        FrmBajaMaterial baja = new FrmBajaMaterial(materialesList);
        baja.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBajaMaterialActionPerformed

    private void btnConsultarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMaterialActionPerformed
       List<Material> materialesC = negocio.recuperaMaterial();
       FrmEditarMaterial consultar = new FrmEditarMaterial(materialesC);
       consultar.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnConsultarMaterialActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajaMaterial;
    private javax.swing.JButton btnConsultarMaterial;
    private javax.swing.JButton btnRegistrarMaterial;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitle;
    // End of variables declaration//GEN-END:variables
}
