/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.futuresoft.sistemamovagro_presentacion;

import com.futuresoft.sistemamovagro_dominio.Material;
import com.futuresoft.sistemamovagro_dominio.Proveedor;
import com.futuresoft.sistemamovagro_negocio.FachadaNegocio;
import com.futuresoft.sistemamovagro_negocio.INegocio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jctri
 */
public class FrmEditarMaterial extends javax.swing.JFrame {
    INegocio negocio;
    List<Material> material;
    /**
     * Creates new form FrmConsultarMaterial
     */
    public FrmEditarMaterial(List<Material> materiales) {
        negocio = new FachadaNegocio();
        initComponents();
        this.material = new ArrayList<>();
        mostrarMaterialesEnTabla(materiales);
    }

    public void mostrarMaterialesEnTabla(List<Material> materiales) {
        DefaultTableModel modelo = (DefaultTableModel) TablaConsultas.getModel();
        modelo.setRowCount(0);

        for (Material material : materiales) {
            Object[] fila = new Object[5];

            fila[0] = material.getId();
            fila[1] = material.getNombre();
            fila[2] = material.getDescripcion();
            fila[3] = material.getUnidadMedida();
            fila[4] = material.getProveedor();

            modelo.addRow(fila);
        }
    }
    
    public void editarFilaSeleccionada() {
        int filaSeleccionada = TablaConsultas.getSelectedRow();
        if (filaSeleccionada >= 0) {
            
            DefaultTableModel modelo = (DefaultTableModel) TablaConsultas.getModel();
            int id = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 0).toString());
            String nombre = modelo.getValueAt(filaSeleccionada, 1).toString();
            String descripcion = modelo.getValueAt(filaSeleccionada, 2).toString();
            String unidadMedida = modelo.getValueAt(filaSeleccionada, 3).toString();
            Proveedor proveedor = (Proveedor) modelo.getValueAt(filaSeleccionada, 4);
            
            String nuevoNombre = JOptionPane.showInputDialog(null, "Editar Nombre:", nombre);
            String nuevaDescripcion = JOptionPane.showInputDialog(null, "Editar Descripcion:", descripcion);
            String nuevaunidadMedida = JOptionPane.showInputDialog(null, "Editar Unidad de Medida:", unidadMedida);


            for (Material materialList : material) {
                if(materialList.getId() == id){
                    materialList.setNombre(nuevoNombre);
                    materialList.setDescripcion(nuevaDescripcion);
                    materialList.setUnidadMedida(nuevaunidadMedida);
                }
            }          
            
            Material materialActualizar = new Material();
            materialActualizar.setId(id);
            materialActualizar.setNombre(nuevoNombre);
            materialActualizar.setDescripcion(nuevaDescripcion);
            materialActualizar.setUnidadMedida(nuevaunidadMedida);
            materialActualizar.setProveedor(proveedor);
            
            negocio.editarMaterial(materialActualizar);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecciona una fila para editar.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsultas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Unidad_Medida", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaConsultas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 66, 561, 196));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Editar Material");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 6, -1, -1));

        btnVolver.setBackground(new java.awt.Color(204, 204, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 177, 73, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 113, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmAdministrarMaterial adminMat = new FrmAdministrarMaterial();
        adminMat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       editarFilaSeleccionada();
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaConsultas;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
